=== even-uia/RRS-Quiz/xml/boatdef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="boatdef" xmlns="boatdef"
           elementFormDefault="qualified">

  <xs:element name="boatdefs" type="boatdefs"/>

  <xs:complexType name="boatdefs">
    <xs:sequence>
      <xs:element name="boattype" type="boattype" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="hull" type="hull" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="rig" type="rig" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="performance" type="performance" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="boattype">
    <xs:sequence>
      <xs:choice>
        <xs:element name="hull" type="hull"/>
        <xs:element name="hullref" type="hullref"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="rig" type="rig"/>
        <xs:element name="rigref" type="rigref"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="performance" type="performance"/>
        <xs:element name="perfref" type="perfref"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>


  <!-- Hull Definition -->
  <xs:complexType name="hullref">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="hull">
    <xs:sequence>
      <xs:element type="point" name="start"/>
      <xs:choice maxOccurs="unbounded">
        <xs:element type="lineto" name="line"/>
        <xs:element type="spline2" name="spline2"/>
        <xs:element type="spline3" name="spline3"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="length" type="xs:integer"/>
    <xs:attribute name="beam" type="xs:integer"/>
  </xs:complexType>


  <xs:complexType name="point">
    <xs:attributeGroup ref="point"/>
  </xs:complexType>

  <xs:complexType name="lineto">
    <xs:attributeGroup ref="point"/>
  </xs:complexType>
  <xs:complexType name="spline2">
    <xs:attributeGroup ref="spline2"/>
  </xs:complexType>
  <xs:complexType name="spline3">
    <xs:attributeGroup ref="spline3"/>
  </xs:complexType>

  <xs:attributeGroup name="point">
    <xs:attribute name="x" type="xs:decimal" use="required"/>
    <xs:attribute name="y" type="xs:decimal" use="required"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="spline2">
    <xs:attributeGroup ref="point"/>
    <xs:attribute name="cx1" type="xs:decimal" use="required"/>
    <xs:attribute name="cy1" type="xs:decimal" use="required"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="spline3">
    <xs:attributeGroup ref="spline2"/>
    <xs:attribute name="cx2" type="xs:decimal" use="required"/>
    <xs:attribute name="cy2" type="xs:decimal" use="required"/>
  </xs:attributeGroup>


  <!-- Rig Definition -->
  <xs:complexType name="rigref">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="rig">
    <xs:sequence>
      <xs:element name="spinpole" type="SpinPole" minOccurs="0" maxOccurs="1"/>
      <xs:element name="sail" type="sail" minOccurs="0" maxOccurs="3"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="mastpos" type="xs:decimal" use="required"/>
    <xs:attribute name="forestaypos" type="xs:decimal" />
    <xs:attribute name="length" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SpinPole">
    <xs:attribute name="length" type="xs:decimal"/>
  </xs:complexType>

  <xs:complexType name="sail">
    <xs:attribute name="type" type="sailtype"/>
    <xs:attribute name="chord" type="xs:decimal"/>
    <xs:attribute name="camber" type="xs:decimal"/>
    <xs:attribute name="minangle" type="xs:decimal"/>
    <xs:attribute name="maxangle" type="xs:decimal"/>
    <xs:attribute name="mintwa" type="xs:decimal"/>
  </xs:complexType>

  <xs:simpleType name="sailtype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="main"/>
      <xs:enumeration value="jib"/>
      <xs:enumeration value="spinnaker"/>
      <xs:enumeration value="gennaker"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- performance -->
  <xs:complexType name="perfref">
    <xs:attribute name="id" type="xs:IDREF"/>
  </xs:complexType>


  <xs:complexType name="performance">
    <xs:sequence>
      <xs:element name="polar" type="polar"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="polar">
    <xs:sequence>
      <xs:element name="data" type="polardata" minOccurs="3" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="polardata">
    <xs:attribute name="twa" type="heading"/>
    <xs:attribute name="speed" type="xs:decimal"/>
  </xs:complexType>

  <xs:simpleType name="heading">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="180"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== even-uia/RRS-Quiz/xml/boatdefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<boatdefs xmlns="boatdef"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="boatdef boatdef.xsd">


  <boattype name="skiff">
    <hullref id="skiffhull"/>
    <rigref id="skiffrig" />
    <perfref id="skiffperf"/>
  </boattype>

  <hull id="skiffhull" beam="3" length="5">
    <start x="0" y="2.5"/>
    <line x="0.6" x="0"/>
    <line x="1.5" y="0.3" />
    <line x="1.5" y="5"/>
    <line x="0.6" y="4.8"/>
    <line x="0" y="4.8"/>
  </hull>

  <rig  id="skiffrig">
    <forestay pos="2.5 render="false" id="forestay"/>
      <mast pos="0" diameter="0.07" id="mast"/>
      <main chord="3" camber="0.06" attachedto="mast"/>
      <jib chord="2" camber="0.06"/>
      <sprit id="sprit" diameter="0.05" len="2" minangle="0" maxangle="0" attachedto="forestay"/>x
      <gennaker chord="3" camber="0.15" attachedto="sprit"/>
  </rig>

  <performance id="skiffperf" >
    <polar >
      <data twa="0"speed="0"/>
      <data twa="25"speed="5"/>
      <data twa="40"speed="10"/>
      <data twa="50"speed="11"/>
      <data twa="90"speed="12"/>
      <data twa="120"speed="12"/>
      <data twa="140"speed="17"/>
      <data twa="150"speed="17"/>
      <data twa="160"speed="15"/>
      <data twa="170"speed="8"/>
      <data twa="180"speed="5"/>
    </polar>
  </performance>

</boatdefs>
